//! The series family's storage (timeseries spec §4.4–§4.7): one
//! bitemporal, append-only table per dataset and a coverage table beside
//! it. There is no live/archive pair and no generation: "live" is the
//! latest `received_at` per `(source, series_id, ts)`, and as-of is a
//! filter on `received_at`. `append_series` is the ONE door rows enter
//! by, whatever produced them — a fetch today, a tail later.
//!
//! Both timestamps are UTC stored as naive `TIMESTAMP`, bound and read as
//! epoch microseconds (`make_timestamp` / `epoch_us`), so no session time
//! zone can shift them. The staging table is the fixed global
//! `staging_series` — one writer, the ingest thread — for the reason
//! `docs/ingest-cold-start-handoff.md` records.

use crate::adapter::SeriesRows;
use crate::store::{Store, StoreError};
use chrono::{DateTime, Utc};
use duckdb::Connection;
use geode_core::schema::{DatasetSpec, SERIES_COLUMNS};

pub const STAGING_TABLE: &str = "staging_series";

pub type Span = (DateTime<Utc>, DateTime<Utc>);

pub fn series_table(dataset: &str) -> String {
    format!("{dataset}_series")
}

pub fn coverage_table(dataset: &str) -> String {
    format!("{dataset}_series_coverage")
}

pub fn micros(t: DateTime<Utc>) -> i64 {
    t.timestamp_micros()
}

pub fn from_micros(us: i64) -> DateTime<Utc> {
    DateTime::<Utc>::from_timestamp_micros(us).expect("a stored timestamp is in range")
}

/// The DDL type for each of `SERIES_COLUMNS`, positionally: zipping the
/// two is what makes `create_series_tables_sql`'s column list generated
/// from `SERIES_COLUMNS` rather than a hand-typed copy that could drift
/// from it.
const SERIES_TYPES: [&str; 5] = ["VARCHAR", "VARCHAR", "TIMESTAMP", "TIMESTAMP", "DOUBLE"];

/// The two `CREATE TABLE IF NOT EXISTS` statements a series dataset
/// owns. The series table's columns are generated by zipping
/// `SERIES_COLUMNS` with `SERIES_TYPES`, so the DDL cannot name a column
/// `SERIES_COLUMNS` does not have (or type one differently) — the
/// primary key names the first four (every column but `value`).
pub fn create_series_tables_sql(ds: &DatasetSpec) -> Vec<String> {
    let columns: Vec<String> = SERIES_COLUMNS
        .iter()
        .zip(SERIES_TYPES)
        .map(|(name, ty)| format!("  \"{name}\" {ty}"))
        .collect();
    let key = SERIES_COLUMNS[..4]
        .iter()
        .map(|c| format!("\"{c}\""))
        .collect::<Vec<_>>()
        .join(", ");
    vec![
        format!(
            "CREATE TABLE IF NOT EXISTS {} (\n{},\n  PRIMARY KEY ({key})\n);",
            series_table(&ds.name),
            columns.join(",\n"),
        ),
        format!(
            "CREATE TABLE IF NOT EXISTS {} (\n  \"source\" VARCHAR,\n  \"series_id\" VARCHAR,\n  \
             \"from_ts\" TIMESTAMP,\n  \"to_ts\" TIMESTAMP,\n  \"received_at\" TIMESTAMP\n);",
            coverage_table(&ds.name)
        ),
    ]
}

pub struct SeriesAppendRequest<'a> {
    pub dataset: &'a DatasetSpec,
    pub source: &'a str,
    pub identity: &'a str,
    pub rows: &'a SeriesRows,
    /// The half-open span this fetch covered, recorded whether or not any
    /// row was new — an empty gap is not asked for again.
    pub span: Span,
    pub received_at: DateTime<Utc>,
}

#[derive(Debug, PartialEq, Eq)]
pub struct SeriesAppended {
    pub appended: usize,
    /// Rows the per-pair retention sweep (§4.7) deleted in the same
    /// transaction.
    pub swept: usize,
}

fn sql_err(statement: &str) -> impl FnOnce(duckdb::Error) -> StoreError + '_ {
    move |source| StoreError::Sql {
        statement: statement.to_string(),
        source,
    }
}

pub fn append_series(
    store: &Store,
    req: &SeriesAppendRequest,
) -> Result<SeriesAppended, StoreError> {
    // Before anything is written: malformed rows leave the store exactly
    // as it was, coverage included.
    req.rows
        .validate()
        .map_err(|e| StoreError::Series(e.message))?;
    let conn = store.writer();
    let table = series_table(&req.dataset.name);
    let coverage = coverage_table(&req.dataset.name);

    // 1. Stage as BIGINT micros: position lines the insert up, and a
    // micros column cannot be bent by a session time zone.
    let create =
        format!("create or replace table {STAGING_TABLE} (\"ts_us\" BIGINT, \"value\" DOUBLE)");
    conn.execute_batch(&create).map_err(sql_err(&create))?;
    {
        let mut app = conn
            .appender(STAGING_TABLE)
            .map_err(sql_err("appender on staging_series"))?;
        for i in 0..req.rows.len() {
            app.append_row(duckdb::params![micros(req.rows.ts[i]), req.rows.value[i]])
                .map_err(sql_err("append row into staging_series"))?;
        }
        app.flush().map_err(sql_err("flush staging_series"))?;
    }

    conn.execute_batch("begin;").map_err(sql_err("begin"))?;
    match append_in_transaction(conn, req, &table, &coverage) {
        Ok(out) => {
            conn.execute_batch("commit;").map_err(sql_err("commit"))?;
            Ok(out)
        }
        Err(e) => {
            let _ = conn.execute_batch("rollback;");
            Err(e)
        }
    }
}

fn append_in_transaction(
    conn: &Connection,
    req: &SeriesAppendRequest,
    table: &str,
    coverage: &str,
) -> Result<SeriesAppended, StoreError> {
    let received = micros(req.received_at);
    // 2. Drop a staged row equal to the LIVE value for its ts, so an
    // overlapping refetch grows nothing. Live is the greatest
    // received_at per ts, expressed inline.
    let dedupe = format!(
        "delete from {STAGING_TABLE} s where exists (
             select 1 from (
                 select ts, arg_max(value, received_at) as v from {table}
                 where source = ? and series_id = ? group by ts
             ) live
             where live.ts = make_timestamp(s.ts_us) and live.v = s.value
         )"
    );
    conn.execute(&dedupe, duckdb::params![req.source, req.identity])
        .map_err(sql_err(&dedupe))?;
    // 3. Insert what remains under one received_at.
    let insert = format!(
        "insert into {table} (source, series_id, ts, received_at, value)
         select ?, ?, make_timestamp(ts_us), make_timestamp(?), value from {STAGING_TABLE}"
    );
    let appended = conn
        .execute(&insert, duckdb::params![req.source, req.identity, received])
        .map_err(sql_err(&insert))?;
    // 4. Coverage, always.
    let cover = format!(
        "insert into {coverage} (source, series_id, from_ts, to_ts, received_at)
         values (?, ?, make_timestamp(?), make_timestamp(?), make_timestamp(?))"
    );
    conn.execute(
        &cover,
        duckdb::params![
            req.source,
            req.identity,
            micros(req.span.0),
            micros(req.span.1),
            received
        ],
    )
    .map_err(sql_err(&cover))?;
    // 5. Retention for this pair, in the same transaction (§4.7): the
    // one place growth happens is the one place it is bounded.
    let swept = sweep_pair(conn, req.dataset, req.source, req.identity, req.received_at)?;
    Ok(SeriesAppended { appended, swept })
}

/// `now` minus `window` in epoch microseconds, or `None` when the window
/// is not representable there.
///
/// `retention`/`history` are user-configured and unbounded in magnitude —
/// `source_config::parse_duration` accepts `y`, so `"300000000y"` is a
/// window whose microseconds exceed `i64::MAX`. Cast rather than
/// converted, such a window wraps NEGATIVE, the cutoff becomes an instant
/// far in the future, and both of `sweep_pair`'s predicates match every
/// row: the pair's whole table and its whole coverage, deleted inside the
/// append's own transaction. `None` means the caller skips that window's
/// deletes entirely — unbounded is the safe direction, and it is the same
/// answer `DataService::fetch` gives an unrepresentable window on the
/// request side (no clip).
fn cutoff(now: DateTime<Utc>, window: std::time::Duration) -> Option<i64> {
    i64::try_from(window.as_micros())
        .ok()
        .and_then(|w| micros(now).checked_sub(w))
}

/// The series family's retention (timeseries spec §4.7), for ONE pair,
/// run inside `append_series`'s transaction with `now` = the append's
/// `received_at`. `retention` deletes rows that are superseded (a later
/// `received_at` exists for the same ts) and older than the window; the
/// live row survives whatever its age. `history` deletes rows and
/// coverage whose `ts`/`to_ts` are older than the window.
///
/// A window whose microseconds do not fit an `i64`, or whose subtraction
/// leaves the representable range, sweeps NOTHING (see [`cutoff`]).
///
/// A span that is already older than `history` when appended is inserted
/// and then swept in the same transaction, coverage included, so a
/// direct caller sees `appended == swept` and no trace remains
/// afterwards. The service never sends such a span — it clips a fetch to
/// the history window before subtracting coverage (timeseries spec
/// §4.7 as built) — so this is reachable only by calling `append_series`
/// directly.
pub fn sweep_pair(
    conn: &Connection,
    ds: &DatasetSpec,
    source: &str,
    identity: &str,
    now: DateTime<Utc>,
) -> Result<usize, StoreError> {
    let Some(policy) = ds.series_retention else {
        return Ok(0);
    };
    let table = series_table(&ds.name);
    let mut swept = 0;
    if let Some(window) = policy.retention
        && let Some(cutoff) = cutoff(now, window)
    {
        let sql = format!(
            "delete from {table} t where source = ? and series_id = ? \
             and epoch_us(received_at) < ? \
             and exists (select 1 from {table} n where n.source = t.source \
                 and n.series_id = t.series_id and n.ts = t.ts and n.received_at > t.received_at)"
        );
        swept += conn
            .execute(&sql, duckdb::params![source, identity, cutoff])
            .map_err(sql_err(&sql))?;
    }
    if let Some(window) = policy.history
        && let Some(cutoff) = cutoff(now, window)
    {
        let sql =
            format!("delete from {table} where source = ? and series_id = ? and epoch_us(ts) < ?");
        swept += conn
            .execute(&sql, duckdb::params![source, identity, cutoff])
            .map_err(sql_err(&sql))?;
        let sql = format!(
            "delete from {} where source = ? and series_id = ? and epoch_us(to_ts) <= ?",
            coverage_table(&ds.name)
        );
        conn.execute(&sql, duckdb::params![source, identity, cutoff])
            .map_err(sql_err(&sql))?;
    }
    Ok(swept)
}

/// Sorts `spans` and merges any that overlap or touch, in place.
pub fn merge_spans(spans: &mut Vec<Span>) {
    spans.retain(|(f, t)| f < t);
    spans.sort();
    let mut out: Vec<Span> = Vec::with_capacity(spans.len());
    for &(f, t) in spans.iter() {
        match out.last_mut() {
            Some(last) if f <= last.1 => last.1 = last.1.max(t),
            _ => out.push((f, t)),
        }
    }
    *spans = out;
}

/// `requested` minus the union of `loaded`: the spans a fetch still has
/// to ask the source for. Pure, so the service thread can run it over the
/// coverage rows it read (timeseries spec §4.6).
pub fn missing_spans(requested: Span, loaded: &[Span]) -> Vec<Span> {
    let (from, to) = requested;
    if from >= to {
        return Vec::new();
    }
    let mut loaded = loaded.to_vec();
    merge_spans(&mut loaded);
    let mut out = Vec::new();
    let mut cursor = from;
    for (f, t) in loaded {
        if t <= cursor {
            continue;
        }
        if f >= to {
            break;
        }
        if f > cursor {
            out.push((cursor, f));
        }
        cursor = cursor.max(t);
        if cursor >= to {
            return out;
        }
    }
    if cursor < to {
        out.push((cursor, to));
    }
    out
}

/// The pair's loaded spans, merged. A coverage row is written per fetch
/// (`append_series` step 4), so this is the union of every fetch so far.
pub fn coverage(
    conn: &Connection,
    dataset: &str,
    source: &str,
    identity: &str,
) -> Result<Vec<Span>, StoreError> {
    let sql = format!(
        "select epoch_us(from_ts), epoch_us(to_ts) from {} where source = ? and series_id = ? \
         order by from_ts",
        coverage_table(dataset)
    );
    let mut stmt = conn.prepare(&sql).map_err(sql_err(&sql))?;
    let rows = stmt
        .query_map(duckdb::params![source, identity], |r| {
            Ok((
                from_micros(r.get::<_, i64>(0)?),
                from_micros(r.get::<_, i64>(1)?),
            ))
        })
        .map_err(sql_err(&sql))?;
    let mut spans = Vec::new();
    for row in rows {
        spans.push(row.map_err(sql_err(&sql))?);
    }
    merge_spans(&mut spans);
    Ok(spans)
}

/// One row per pair from the coverage table (timeseries spec §4.6):
/// the hull of its fetched spans, how many fetches, and the newest
/// `received_at`. Coverage is one row per fetch, so this is
/// catalog-sized and never scans the series table — the rule
/// `query::catalog::build_catalog` states.
pub fn series_catalog(
    conn: &Connection,
    dataset: &str,
) -> Result<Vec<geode_core::query::SeriesCatalog>, StoreError> {
    let sql = format!(
        "select source, series_id, epoch_us(min(from_ts)), epoch_us(max(to_ts)), count(*), \
         epoch_us(max(received_at)) from {} group by source, series_id order by series_id, source",
        coverage_table(dataset)
    );
    let mut stmt = conn.prepare(&sql).map_err(sql_err(&sql))?;
    let rows = stmt
        .query_map([], |r| {
            Ok(geode_core::query::SeriesCatalog {
                source: r.get(0)?,
                identity: r.get(1)?,
                from: from_micros(r.get::<_, i64>(2)?),
                to: from_micros(r.get::<_, i64>(3)?),
                fetches: r.get::<_, i64>(4)? as u64,
                latest_received_at: from_micros(r.get::<_, i64>(5)?),
            })
        })
        .map_err(sql_err(&sql))?;
    let mut out = Vec::new();
    for row in rows {
        out.push(row.map_err(sql_err(&sql))?);
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::store::Store;
    use crate::store::catalog::Catalog;
    use crate::store::ddl::tests_support::{series_dataset, series_rows, ts};
    use proptest::prelude::*;

    fn fixture() -> (tempfile::TempDir, Store, DatasetSpec) {
        let dir = tempfile::tempdir().unwrap();
        let store = Store::open(dir.path().join("geode.duckdb")).unwrap();
        let ds = series_dataset();
        store.apply_schema(&ds).unwrap();
        Catalog::new(store.writer()).ensure_tables().unwrap();
        (dir, store, ds)
    }

    fn append(
        store: &Store,
        ds: &DatasetSpec,
        rows: &SeriesRows,
        span: (&str, &str),
        at: &str,
    ) -> SeriesAppended {
        append_series(
            store,
            &SeriesAppendRequest {
                dataset: ds,
                source: "demo_kdb",
                identity: "SPX.close",
                rows,
                span: (ts(span.0), ts(span.1)),
                received_at: ts(at),
            },
        )
        .unwrap()
    }

    /// `(epoch micros of ts, epoch micros of received_at, value)` for the
    /// pair, oldest first, every version — the raw table, not the live view.
    fn all_rows(store: &Store) -> Vec<(i64, i64, f64)> {
        let mut stmt = store
            .writer()
            .prepare(
                "select epoch_us(ts), epoch_us(received_at), value from series_series \
                 where source = 'demo_kdb' and series_id = 'SPX.close' order by ts, received_at",
            )
            .unwrap();
        stmt.query_map([], |r| Ok((r.get(0)?, r.get(1)?, r.get(2)?)))
            .unwrap()
            .collect::<Result<_, _>>()
            .unwrap()
    }

    #[test]
    fn a_first_append_lands_every_row_stamped_with_received_at() {
        let (_d, store, ds) = fixture();
        let rows = series_rows("2026-01-05T14:30:00Z", 3, 100.0);
        let out = append(
            &store,
            &ds,
            &rows,
            ("2026-01-05T00:00:00Z", "2026-01-06T00:00:00Z"),
            "2026-01-06T09:00:00Z",
        );
        assert_eq!(
            out,
            SeriesAppended {
                appended: 3,
                swept: 0
            }
        );
        let got = all_rows(&store);
        assert_eq!(got.len(), 3);
        assert_eq!(
            got[0],
            (
                micros(ts("2026-01-05T14:30:00Z")),
                micros(ts("2026-01-06T09:00:00Z")),
                100.0
            )
        );
        assert_eq!(got[2].0, micros(ts("2026-01-05T14:32:00Z")));
        let cov: (i64, i64, i64) = store
            .writer()
            .query_row(
                "select epoch_us(from_ts), epoch_us(to_ts), count(*) over () from series_series_coverage",
                [],
                |r| Ok((r.get(0)?, r.get(1)?, r.get(2)?)),
            )
            .unwrap();
        assert_eq!(
            cov,
            (
                micros(ts("2026-01-05T00:00:00Z")),
                micros(ts("2026-01-06T00:00:00Z")),
                1
            )
        );
    }

    #[test]
    fn an_overlapping_refetch_with_the_same_values_appends_nothing_but_records_coverage() {
        let (_d, store, ds) = fixture();
        let rows = series_rows("2026-01-05T14:30:00Z", 3, 100.0);
        append(
            &store,
            &ds,
            &rows,
            ("2026-01-05T00:00:00Z", "2026-01-06T00:00:00Z"),
            "2026-01-06T09:00:00Z",
        );
        let again = append(
            &store,
            &ds,
            &rows,
            ("2026-01-05T00:00:00Z", "2026-01-06T00:00:00Z"),
            "2026-01-07T09:00:00Z",
        );
        assert_eq!(again.appended, 0);
        assert_eq!(all_rows(&store).len(), 3, "the table did not grow");
        let n: i64 = store
            .writer()
            .query_row("select count(*) from series_series_coverage", [], |r| {
                r.get(0)
            })
            .unwrap();
        assert_eq!(n, 2, "coverage is recorded even when nothing was new");
    }

    #[test]
    fn a_corrected_value_is_one_more_row_and_the_older_one_survives() {
        let (_d, store, ds) = fixture();
        let rows = series_rows("2026-01-05T14:30:00Z", 1, 100.0);
        append(
            &store,
            &ds,
            &rows,
            ("2026-01-05T00:00:00Z", "2026-01-06T00:00:00Z"),
            "2026-01-06T09:00:00Z",
        );
        let corrected = series_rows("2026-01-05T14:30:00Z", 1, 101.0);
        let out = append(
            &store,
            &ds,
            &corrected,
            ("2026-01-05T00:00:00Z", "2026-01-06T00:00:00Z"),
            "2026-01-07T09:00:00Z",
        );
        assert_eq!(out.appended, 1);
        let got = all_rows(&store);
        assert_eq!(got.len(), 2);
        assert_eq!((got[0].2, got[1].2), (100.0, 101.0));
        assert!(
            got[1].1 > got[0].1,
            "the correction has the later received_at"
        );
    }

    #[test]
    fn an_empty_fetch_records_coverage_and_appends_nothing() {
        let (_d, store, ds) = fixture();
        let out = append(
            &store,
            &ds,
            &SeriesRows::default(),
            ("2026-01-03T00:00:00Z", "2026-01-04T00:00:00Z"),
            "2026-01-06T09:00:00Z",
        );
        assert_eq!(
            out,
            SeriesAppended {
                appended: 0,
                swept: 0
            }
        );
        let n: i64 = store
            .writer()
            .query_row("select count(*) from series_series_coverage", [], |r| {
                r.get(0)
            })
            .unwrap();
        assert_eq!(n, 1);
    }

    #[test]
    fn invalid_rows_are_refused_before_anything_is_written() {
        let (_d, store, ds) = fixture();
        let bad = SeriesRows {
            ts: vec![ts("2026-01-05T14:30:00Z")],
            value: vec![1.0, 2.0],
        };
        let err = append_series(
            &store,
            &SeriesAppendRequest {
                dataset: &ds,
                source: "demo_kdb",
                identity: "SPX.close",
                rows: &bad,
                span: (ts("2026-01-05T00:00:00Z"), ts("2026-01-06T00:00:00Z")),
                received_at: ts("2026-01-06T09:00:00Z"),
            },
        )
        .unwrap_err();
        assert!(matches!(err, StoreError::Series(_)), "{err}");
        assert!(all_rows(&store).is_empty());
        let n: i64 = store
            .writer()
            .query_row("select count(*) from series_series_coverage", [], |r| {
                r.get(0)
            })
            .unwrap();
        assert_eq!(n, 0);
    }

    #[test]
    fn micros_round_trip() {
        let t = ts("2026-01-05T14:30:00Z");
        assert_eq!(from_micros(micros(t)), t);
    }

    #[test]
    fn the_series_ddl_names_the_five_columns_in_order() {
        let sql = &create_series_tables_sql(&series_dataset())[0];
        let mut last = 0isize;
        for needle in [
            "\"source\" VARCHAR",
            "\"series_id\" VARCHAR",
            "\"ts\" TIMESTAMP",
            "\"received_at\" TIMESTAMP",
            "\"value\" DOUBLE",
        ] {
            let at = sql
                .find(needle)
                .unwrap_or_else(|| panic!("{needle:?} missing from {sql}"))
                as isize;
            assert!(at > last, "{needle:?} out of order in {sql}");
            last = at;
        }

        // The coverage table's statement is unchanged in meaning: its own
        // five columns, none of them borrowed from `SERIES_COLUMNS`.
        let coverage_sql = &create_series_tables_sql(&series_dataset())[1];
        for needle in [
            "\"source\" VARCHAR",
            "\"series_id\" VARCHAR",
            "\"from_ts\" TIMESTAMP",
            "\"to_ts\" TIMESTAMP",
            "\"received_at\" TIMESTAMP",
        ] {
            assert!(
                coverage_sql.contains(needle),
                "{needle:?} missing from {coverage_sql}"
            );
        }
    }

    #[test]
    fn a_third_append_of_the_original_value_re_appends_because_live_is_the_correction() {
        let (_d, store, ds) = fixture();
        let span = ("2026-01-05T00:00:00Z", "2026-01-06T00:00:00Z");
        let original = series_rows("2026-01-05T14:30:00Z", 1, 100.0);
        append(&store, &ds, &original, span, "2026-01-06T09:00:00Z");
        let corrected = series_rows("2026-01-05T14:30:00Z", 1, 101.0);
        let out = append(&store, &ds, &corrected, span, "2026-01-07T09:00:00Z");
        assert_eq!(out.appended, 1);
        // Live is now 101.0 (the greatest received_at). Re-offering the
        // ORIGINAL value is a third, distinct version, not a no-op: the
        // dedupe compares against live, never against every version ever
        // seen.
        let original_again = series_rows("2026-01-05T14:30:00Z", 1, 100.0);
        let out = append(&store, &ds, &original_again, span, "2026-01-08T09:00:00Z");
        assert_eq!(out.appended, 1);
        let got = all_rows(&store);
        assert_eq!(got.len(), 3);
        assert_eq!(
            got.iter().map(|r| r.2).collect::<Vec<_>>(),
            vec![100.0, 101.0, 100.0],
            "in received_at order: {got:?}"
        );
    }

    #[test]
    fn retention_deletes_superseded_rows_older_than_the_window_and_keeps_live() {
        let (_d, store, ds) = fixture(); // retention = 30d, history = 5y
        let old = series_rows("2026-01-05T14:30:00Z", 1, 100.0);
        append(
            &store,
            &ds,
            &old,
            ("2026-01-05T00:00:00Z", "2026-01-06T00:00:00Z"),
            "2026-01-06T09:00:00Z",
        );
        let corrected = series_rows("2026-01-05T14:30:00Z", 1, 101.0);
        // 10 days later: the superseded row is inside the 30d window, kept.
        let out = append(
            &store,
            &ds,
            &corrected,
            ("2026-01-05T00:00:00Z", "2026-01-06T00:00:00Z"),
            "2026-01-16T09:00:00Z",
        );
        assert_eq!(out.swept, 0);
        assert_eq!(all_rows(&store).len(), 2);
        // 40 days after the first: the superseded row is outside it, swept;
        // the live row (101.0) survives whatever its age.
        let untouched = series_rows("2026-01-05T14:31:00Z", 1, 5.0);
        let out = append(
            &store,
            &ds,
            &untouched,
            ("2026-01-05T00:00:00Z", "2026-01-06T00:00:00Z"),
            "2026-02-20T09:00:00Z",
        );
        assert_eq!(out.swept, 1);
        let got = all_rows(&store);
        assert_eq!(
            got.iter().map(|r| r.2).collect::<Vec<_>>(),
            vec![101.0, 5.0]
        );
    }

    #[test]
    fn history_deletes_rows_and_coverage_whose_ts_is_too_old() {
        let (_d, store, ds) = fixture(); // history = 5y
        let ancient = series_rows("2019-01-05T14:30:00Z", 2, 1.0);
        append(
            &store,
            &ds,
            &ancient,
            ("2019-01-05T00:00:00Z", "2019-01-06T00:00:00Z"),
            "2019-01-06T09:00:00Z",
        );
        let recent = series_rows("2026-01-05T14:30:00Z", 1, 100.0);
        let out = append(
            &store,
            &ds,
            &recent,
            ("2026-01-05T00:00:00Z", "2026-01-06T00:00:00Z"),
            "2026-01-06T09:00:00Z",
        );
        assert_eq!(out.swept, 2);
        assert_eq!(all_rows(&store).len(), 1);
        let cov = coverage(store.writer(), "series", "demo_kdb", "SPX.close").unwrap();
        assert_eq!(
            cov,
            vec![sp("2026-01-05T00:00:00Z", "2026-01-06T00:00:00Z")],
            "the ancient coverage row went with its rows"
        );
    }

    #[test]
    fn a_span_entirely_outside_history_is_swept_by_its_own_append() {
        let (_d, store, ds) = fixture(); // history = 5y
        let ancient = series_rows("2019-01-05T14:30:00Z", 2, 1.0);
        let out = append(
            &store,
            &ds,
            &ancient,
            ("2019-01-05T00:00:00Z", "2019-01-06T00:00:00Z"),
            "2026-01-06T09:00:00Z",
        );
        assert_eq!(
            out,
            SeriesAppended {
                appended: 2,
                swept: 2
            }
        );
        assert!(all_rows(&store).is_empty());
        assert!(
            coverage(store.writer(), "series", "demo_kdb", "SPX.close")
                .unwrap()
                .is_empty(),
            "the coverage row went with the rows"
        );
    }

    /// A series `DatasetSpec` straight from TOML, for the tests that need
    /// a retention policy other than `series_dataset()`'s own.
    fn dataset_from(text: &str) -> DatasetSpec {
        let doc = geode_core::config::merge_docs(
            "datasets",
            &[geode_core::config::LayerDoc::builtin("datasets", text).unwrap()],
        );
        geode_core::schema::SchemaSpec::from_doc(&doc)
            .0
            .dataset("series")
            .unwrap()
            .clone()
    }

    #[test]
    fn an_unbounded_policy_sweeps_nothing() {
        let dir = tempfile::tempdir().unwrap();
        let store = Store::open(dir.path().join("geode.duckdb")).unwrap();
        let ds = dataset_from("[series]\nfamily = \"series\"\n");
        store.apply_schema(&ds).unwrap();
        let a = series_rows("2019-01-05T14:30:00Z", 1, 1.0);
        append(
            &store,
            &ds,
            &a,
            ("2019-01-05T00:00:00Z", "2019-01-06T00:00:00Z"),
            "2019-01-06T09:00:00Z",
        );
        let b = series_rows("2019-01-05T14:30:00Z", 1, 2.0);
        let out = append(
            &store,
            &ds,
            &b,
            ("2019-01-05T00:00:00Z", "2019-01-06T00:00:00Z"),
            "2030-01-06T09:00:00Z",
        );
        assert_eq!(out.swept, 0);
        assert_eq!(all_rows(&store).len(), 2);
    }

    /// `parse_duration` accepts `y`, so a trader can configure a window
    /// whose microseconds exceed `i64::MAX`. Cast rather than converted,
    /// it wraps negative, the cutoff lands tens of thousands of years in
    /// the future and BOTH sweeps match every row — the pair's whole
    /// table and its whole coverage, gone inside the append's own
    /// transaction. Unrepresentable is unbounded, and unbounded sweeps
    /// nothing.
    #[test]
    fn an_unrepresentable_window_sweeps_nothing() {
        let dir = tempfile::tempdir().unwrap();
        let store = Store::open(dir.path().join("geode.duckdb")).unwrap();
        // 3e8 years is 9.46e21 microseconds; `i64::MAX` is 9.22e18.
        let ds = dataset_from(
            "[series]\nfamily = \"series\"\nretention = \"300000000y\"\nhistory = \"300000000y\"\n",
        );
        assert!(
            ds.series_retention
                .unwrap()
                .retention
                .is_some_and(|w| i64::try_from(w.as_micros()).is_err()),
            "the fixture's window must be the unrepresentable one"
        );
        store.apply_schema(&ds).unwrap();
        let first = series_rows("2026-01-05T14:30:00Z", 1, 100.0);
        append(
            &store,
            &ds,
            &first,
            ("2026-01-05T00:00:00Z", "2026-01-06T00:00:00Z"),
            "2026-01-06T09:00:00Z",
        );
        // A year later, a correction for the same ts: the first row is
        // now superseded, which is what the retention sweep deletes.
        let corrected = series_rows("2026-01-05T14:30:00Z", 1, 101.0);
        let out = append(
            &store,
            &ds,
            &corrected,
            ("2026-01-05T00:00:00Z", "2026-01-06T00:00:00Z"),
            "2027-01-06T09:00:00Z",
        );
        assert_eq!(out.swept, 0);
        let got = all_rows(&store);
        assert_eq!(
            got.iter().map(|r| r.2).collect::<Vec<_>>(),
            vec![100.0, 101.0],
            "both versions survive: {got:?}"
        );
        assert_eq!(
            coverage(store.writer(), "series", "demo_kdb", "SPX.close").unwrap(),
            vec![sp("2026-01-05T00:00:00Z", "2026-01-06T00:00:00Z")],
            "and so does the coverage"
        );
    }

    fn sp(a: &str, b: &str) -> Span {
        (ts(a), ts(b))
    }

    #[test]
    fn missing_spans_subtracts_loaded_spans() {
        let req = sp("2026-01-01T00:00:00Z", "2026-01-10T00:00:00Z");
        assert_eq!(missing_spans(req, &[]), vec![req]);
        assert_eq!(missing_spans(req, &[req]), vec![]);
        let loaded = [sp("2026-01-03T00:00:00Z", "2026-01-05T00:00:00Z")];
        assert_eq!(
            missing_spans(req, &loaded),
            vec![
                sp("2026-01-01T00:00:00Z", "2026-01-03T00:00:00Z"),
                sp("2026-01-05T00:00:00Z", "2026-01-10T00:00:00Z")
            ]
        );
        // A loaded span wider than the request leaves nothing.
        assert_eq!(
            missing_spans(req, &[sp("2025-12-01T00:00:00Z", "2026-02-01T00:00:00Z")]),
            vec![]
        );
        // Touching spans merge: [1,3) and [3,5) leave [5,10).
        assert_eq!(
            missing_spans(
                req,
                &[
                    sp("2026-01-01T00:00:00Z", "2026-01-03T00:00:00Z"),
                    sp("2026-01-03T00:00:00Z", "2026-01-05T00:00:00Z")
                ]
            ),
            vec![sp("2026-01-05T00:00:00Z", "2026-01-10T00:00:00Z")]
        );
        // An empty request is nothing.
        assert_eq!(
            missing_spans(sp("2026-01-05T00:00:00Z", "2026-01-05T00:00:00Z"), &[]),
            vec![]
        );
    }

    #[test]
    fn coverage_reads_back_merged_spans() {
        let (_d, store, ds) = fixture();
        let rows = SeriesRows::default();
        append(
            &store,
            &ds,
            &rows,
            ("2026-01-01T00:00:00Z", "2026-01-03T00:00:00Z"),
            "2026-01-06T09:00:00Z",
        );
        append(
            &store,
            &ds,
            &rows,
            ("2026-01-02T00:00:00Z", "2026-01-05T00:00:00Z"),
            "2026-01-06T09:01:00Z",
        );
        append(
            &store,
            &ds,
            &rows,
            ("2026-01-08T00:00:00Z", "2026-01-09T00:00:00Z"),
            "2026-01-06T09:02:00Z",
        );
        let got = coverage(store.writer(), "series", "demo_kdb", "SPX.close").unwrap();
        assert_eq!(
            got,
            vec![
                sp("2026-01-01T00:00:00Z", "2026-01-05T00:00:00Z"),
                sp("2026-01-08T00:00:00Z", "2026-01-09T00:00:00Z")
            ]
        );
        assert!(
            coverage(store.writer(), "series", "demo_kdb", "VIX")
                .unwrap()
                .is_empty()
        );
    }

    proptest! {
        /// loaded ∪ missing covers requested exactly, and missing is
        /// disjoint from loaded.
        #[test]
        fn missing_and_loaded_partition_the_request(
            req_from in 0i64..1000, req_len in 0i64..1000,
            loaded in prop::collection::vec((0i64..1000, 1i64..300), 0..6),
        ) {
            let base = ts("2026-01-01T00:00:00Z");
            let at = |h: i64| base + chrono::Duration::hours(h);
            let req = (at(req_from), at(req_from + req_len));
            let loaded: Vec<Span> = loaded.iter().map(|(f, l)| (at(*f), at(f + l))).collect();
            let missing = missing_spans(req, &loaded);
            for h in req_from..req_from + req_len {
                let t = at(h);
                let in_loaded = loaded.iter().any(|(f, to)| *f <= t && t < *to);
                let in_missing = missing.iter().any(|(f, to)| *f <= t && t < *to);
                prop_assert_ne!(in_loaded, in_missing, "hour {} must be in exactly one", h);
            }
            for w in missing.windows(2) {
                prop_assert!(w[0].1 <= w[1].0, "missing spans are sorted and disjoint");
            }
            // The hour-by-hour check above cannot see a missing span that
            // runs PAST the request: an hour outside it is in neither
            // loop, so a gap that over-reaches the request's own bounds
            // (and would be fetched from the vendor, then swept) passes
            // every assertion here without this one.
            prop_assert!(
                missing.iter().all(|(f, t)| *f >= req.0 && *t <= req.1),
                "missing spans stay inside the request"
            );
        }
    }

    #[test]
    fn an_equal_value_for_another_series_still_lands() {
        let (_d, store, ds) = fixture();
        let span = ("2026-01-05T00:00:00Z", "2026-01-06T00:00:00Z");
        let rows = series_rows("2026-01-05T14:30:00Z", 1, 100.0);
        append(&store, &ds, &rows, span, "2026-01-06T09:00:00Z");

        // Same source, same ts, same value, but a DIFFERENT series_id: the
        // dedupe's derived table must be filtered to the (source,
        // series_id) pair, never the whole table, or this would be
        // dropped as "already live" for a series it has never seen.
        let out = append_series(
            &store,
            &SeriesAppendRequest {
                dataset: &ds,
                source: "demo_kdb",
                identity: "VIX",
                rows: &rows,
                span: (ts(span.0), ts(span.1)),
                received_at: ts("2026-01-07T09:00:00Z"),
            },
        )
        .unwrap();
        assert_eq!(out.appended, 1);

        let n: i64 = store
            .writer()
            .query_row(
                "select count(*) from series_series where series_id = 'VIX'",
                [],
                |r| r.get(0),
            )
            .unwrap();
        assert_eq!(n, 1);
    }
}
